- name: Gather facts
  hosts: all
  become: yes

- name: Failover PostgreSQL
  hosts: database_replica
  become: yes
  vars:
    # edit-here - added pgsql version, path and service name manually
    pgsqlrep_data_path: /var/opt/rh/rh-postgresql10/lib/pgsql/data
    pgsql_version_service : rh-postgresql10-postgresql
    pgsql_bin_path: /opt/rh/rh-postgresql10/root/bin

  tasks:
    - name: Get the current PostgreSQL Version
      import_role:
        name: samdoran.pgsql_replication
        tasks_from: pgsql_version.yml

    - name: Promote secondary PostgreSQL server to primary
      command: pg_ctl promote #/usr/pgsql-{{ pgsql_version }}/bin/pg_ctl promote
      #edit-here added become parameters
      become: yes
      become_user: postgres
      become_flags: 'su - postgres -c'
      environment:
        PGDATA: "{{ pgsqlrep_data_path }}" #/var/lib/pgsql/{{ pgsql_version }}/data
      ignore_errors: yes

- name: Update Ansible Tower database configuration
  hosts: tower
  become: yes

  tasks:
    - name: Update Tower postgres.py
      lineinfile:
        dest: /etc/tower/conf.d/postgres.py
        regexp: "^(.*'HOST':)"
        line: "\\1 '{{ hostvars[groups['database_replica'][0]].ansible_default_ipv4.address }}',"
        backrefs: yes
      notify: restart tower

  handlers:
    - name: restart tower
      command: ansible-tower-service restart