- name: Stop PostgreSQL
  service:
    # edit-here use manul input for service
    # name: "{{ pgsql_version | pgsql_service_string }}"
    name: "{{ pgsql_version_service }}"   
    state: stopped

- name: Clear out data directory
  file:
    path: "{{ pgsqlrep_data_path }}"
    state: absent

- name: Create empty data directory
  file:
    path: "{{ pgsqlrep_data_path }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Create base backup
  # edit-here added become_flags: 'su - postgres -c' also make sure ansible version is not 2.9.4 (yet to confirm this)
  shell: "pg_basebackup -X stream -D {{ pgsqlrep_data_path }} -h {{ pgsqlrep_master_address }} -U {{ pgsqlrep_user }}"
  become: yes
  become_user: postgres
  become_flags: 'su - postgres -c'

- name: Create recovery.conf
  template:
    src: recovery.conf.j2
    dest: "{{ pgsqlrep_data_path }}/recovery.conf"
    owner: postgres
    group: postgres
    mode: '0644'

- name: Enable hot standby
  lineinfile:
    state: present
    backup: yes
    dest: "{{ pgsqlrep_data_path }}/postgresql.conf"
    regexp: '^#?hot_standby = \w+(\s+#.*)'
    line: 'hot_standby = yes\1'
    backrefs: yes
  become: yes
  become_user: postgres

- name: Start and enable PostgreSQL
  service:
    # edit-here use manul input for service
    # name: "{{ pgsql_version | pgsql_service_string }}"
    name: "{{ pgsql_version_service }}"   
    state: started
    enabled: yes
